services: 
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      DEFAULT_HOST: ${DWPA_VIRTUAL_HOST:-localhost}
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - .docker/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    depends_on:
      - nginx-proxy
    env_file:
      - .env
    environment:
      DEFAULT_EMAIL: $DWPA_MAIL_FROM
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
  web:
    ports: !override
      - 80
    depends_on:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: ${DWPA_VIRTUAL_HOST:-localhost}
      LETSENCRYPT_HOST: ${DWPA_VIRTUAL_HOST:-localhost}
  database:
    ports: !override
      - 3306
  phpmyadmin:
    ports: !override
      - 80
    depends_on:
      - nginx-proxy
    environment: !override
      VIRTUAL_HOST: ${DWPA_VIRTUAL_HOST_PMA:-localhost}
      LETSENCRYPT_HOST: ${DWPA_VIRTUAL_HOST_PMA:-localhost}
      HIDE_PHP_VERSION: "true"
      PMA_HOST: database
      PMA_USER: 
      PMA_PASSWORD: 
volumes:
  conf:
  vhost:
  html:
  certs:
  acme: