services: 
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./dwpa/web:/srv/app
      - ./dwpa/help_crack:/srv/app/hc
      - ./dict:/srv/app/dict
    links:
      - app
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-localhost}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST:-localhost}
    env_file:
      - .env
    restart: always
  app:
    build:
      context: .
      target: runtime
      dockerfile: Dockerfile
    image: dwpa-web-app
    volumes:
      - app-data-cap:/srv/app/cap
      - ./dict:/srv/app/dict
      - ./.docker/conf.php:/srv/app/conf.php
    links:
      - database
    env_file:
      - .env
    restart: always
  database:
    image: mariadb:latest
    command:
      [
        "mariadbd",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT}
    env_file:
      - .env
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
      - database-data:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT}
      UPLOAD_LIMIT: 1G
    env_file:
      - .env
    restart: always
volumes:
  database-data:
  app-data-cap: